import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { dirname, resolve } from 'node:path'

const SERVER_COMMAND = ['vune-ui', 'lsp', '--stdio']

function readJson(path, fallback = undefined) {
  try { return JSON.parse(readFileSync(path, 'utf8')) } catch { return fallback }
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`)
}

function writeText(path, value) {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, value)
}

function nvimConfig() {
  return `-- Vune language server integration. Generated by vune-ui.\nvim.filetype.add({ extension = { ["vune"] = "vune-ui", ["vune.ts"] = "vune-ui" } })\nlocal group = vim.api.nvim_create_augroup("VuneLsp", { clear = true })\nvim.api.nvim_create_autocmd({ "BufReadPost", "BufNewFile" }, {\n  group = group,\n  pattern = { "*.vune", "*.vune.ts", "*.vue" },\n  callback = function(args)\n    vim.lsp.start({\n      name = "vune",\n      cmd = { "${SERVER_COMMAND[0]}", "${SERVER_COMMAND[1]}", "${SERVER_COMMAND[2]}" },\n      root_dir = vim.fs.root(args.buf, { "package.json", ".git" }) or vim.fn.getcwd(),\n    })\n  end,\n})\n`
}

function vimConfig() {
  return `" Vune language server integration. Generated by vune-ui.\nif exists('*lsp#register_server')\n  augroup vune_lsp\n    autocmd!\n    autocmd User lsp_setup call lsp#register_server({\n          \\ 'name': 'vune',\n          \\ 'cmd': {server_info -> ['${SERVER_COMMAND[0]}', '${SERVER_COMMAND[1]}', '${SERVER_COMMAND[2]}']},\n          \\ 'allowlist': ['vune-ui', 'vue']\n          \\ })\n    autocmd BufNewFile,BufRead *.vune,*.vune.ts set filetype=vune-ui\n  augroup END\nendif\n`
}

function zedConfig() {
  return { language_servers: { vune: { command: SERVER_COMMAND[0], args: SERVER_COMMAND.slice(1) } }, languages: { Vune: { file_types: ['vune', 'vune.ts'], language_servers: ['vune'] } } }
}

function helixConfig() {
  return `[language-server.vune]\ncommand = "${SERVER_COMMAND[0]}"\nargs = ["${SERVER_COMMAND[1]}", "${SERVER_COMMAND[2]}"]\n\n[[language]]\nname = "vune"\nfile-types = ["vune", "vune.ts"]\nlanguage-servers = ["vune"]\n`
}

function installEditors({ editor = 'all', projectRoot = process.cwd(), global = false } = {}) {
  const root = global ? homedir() : resolve(projectRoot)
  const target = global ? 'global' : root
  const installed = []
  const selected = editor === 'all' ? new Set(['vim', 'nvim', 'vscode', 'zed', 'helix', 'generic']) : new Set(editor.split(',').map(value => value.trim()).filter(Boolean))
  const unknown = [...selected].filter(value => !['vim', 'nvim', 'vscode', 'zed', 'helix', 'generic'].includes(value))
  if (unknown.length) throw new Error(`Unknown editor: ${unknown.join(', ')}. Use vim, nvim, vscode, zed, helix, generic, or all.`)
  if (selected.has('nvim')) {
    const path = global ? resolve(root, '.config/nvim/lua/vune/lsp.lua') : resolve(root, '.vune/editors/nvim.lua')
    writeText(path, nvimConfig()); installed.push(path)
  }
  if (selected.has('vim')) {
    const path = global ? resolve(root, '.vim/pack/vune/start/vune-lsp/plugin/vune-lsp.vim') : resolve(root, '.vune/editors/vim.vim')
    writeText(path, vimConfig()); installed.push(path)
  }
  if (selected.has('vscode')) {
    const settingsPath = resolve(root, '.vscode/settings.json')
    let settingsOutput = settingsPath
    const settings = readJson(settingsPath, undefined)
    if (settings || !existsSync(settingsPath)) {
      const mergedSettings = settings ?? {}
      mergedSettings['vune.languageTools.enableVue'] = true
      mergedSettings['files.associations'] = { ...(mergedSettings['files.associations'] ?? {}), '*.vune': 'vune-ui', '*.vune.ts': 'vune-ui' }
      writeJson(settingsPath, mergedSettings)
    } else {
      settingsOutput = resolve(root, '.vune/editors/vscode-settings.json')
      writeJson(settingsOutput, {
        'vune.languageTools.enableVue': true,
        'files.associations': { '*.vune': 'vune-ui', '*.vune.ts': 'vune-ui' },
      })
    }
    const extensionsPath = resolve(root, '.vscode/extensions.json')
    let extensionsOutput = extensionsPath
    const extensions = readJson(extensionsPath, undefined)
    if (extensions || !existsSync(extensionsPath)) {
      const mergedExtensions = extensions ?? {}
      mergedExtensions.recommendations = [...new Set([...(mergedExtensions.recommendations ?? []), 'vune-ui.vune-language-support'])]
      writeJson(extensionsPath, mergedExtensions)
    } else {
      extensionsOutput = resolve(root, '.vune/editors/vscode-extensions.json')
      writeText(extensionsOutput, '{\n  "recommendations": ["vune-ui.vune-language-support"]\n}\n')
    }
    installed.push(settingsOutput, extensionsOutput)
  }
  if (selected.has('zed')) {
    const path = global ? resolve(root, '.config/zed/settings.json') : resolve(root, '.vune/editors/zed.json')
    writeJson(path, zedConfig()); installed.push(path)
  }
  if (selected.has('helix')) {
    const path = global ? resolve(root, '.config/helix/languages.toml') : resolve(root, '.vune/editors/helix.toml')
    const existing = existsSync(path) ? readFileSync(path, 'utf8') : ''
    if (!existing.includes('[language-server.vune]')) writeText(path, `${existing}${existing && !existing.endsWith('\n') ? '\n' : ''}${helixConfig()}`)
    installed.push(path)
  }
  if (selected.has('generic')) {
    const path = resolve(root, '.vune/lsp.json')
    writeJson(path, { name: 'vune', command: SERVER_COMMAND[0], args: SERVER_COMMAND.slice(1), transport: 'stdio', fileExtensions: ['.vune', '.vune.ts', '.vue'] })
    installed.push(path)
  }
  console.log(`Installed Vune LSP integration (${[...selected].join(', ')}) for ${target}.`)
  installed.forEach(path => console.log(`  ${path}`))
  return installed
}

export { installEditors, SERVER_COMMAND }
